/*****************************************************************************
*
*                                  chip_reg.h
*
*   Copyright (c) 2015 Shanghai Fullhan Microelectronics Co., Ltd.
*                       All Rights Reserved. Confidential.
*
*   File Description:
*       Chip register definition of the whole chip.
*       Include the address of each hardware register
*
*   Modification History:
*
******************************************************************************/
#ifndef _CHIP_REG_H_
#define _CHIP_REG_H_

/* Includes -----------------------------------------------------------------*/
#include "chip.h"
#include "fh_defs.h"

#define 	REG_AES_CTRL				(AES_REG_BASE + 0x0000)
#define 	REG_AES_FIFO_STATUS			(AES_REG_BASE + 0x0008)
#define 	REG_AES_PERR_STATUS			(AES_REG_BASE + 0x000C)
#define 	REG_AES_KEY0				(AES_REG_BASE + 0x0010)
#define 	REG_AES_IV0				(AES_REG_BASE + 0x0030)
#define 	REG_AES_DMA_SRC				(AES_REG_BASE + 0x0048)
#define 	REG_AES_DMA_DES				(AES_REG_BASE + 0x004C)
#define 	REG_AES_DMA_SIZE			(AES_REG_BASE + 0x0050)
#define 	REG_AES_DMA_CTRL			(AES_REG_BASE + 0x0054)
#define 	REG_AES_FIFO_THOLD			(AES_REG_BASE + 0x0058)
#define 	REG_AES_INTR_EN				(AES_REG_BASE + 0x005C)
#define 	REG_AES_INTR_SRC			(AES_REG_BASE + 0x0060)
#define 	REG_AES_INTR_MASKED_STATUS		(AES_REG_BASE + 0x0064)
#define 	REG_AES_INTR_CLR			(AES_REG_BASE + 0x0068)


#define		REG_EFUSE_CMD				(EFUSE_REG_BASE + 0x0000)
#define		REG_EFUSE_CONFIG			(EFUSE_REG_BASE + 0x0004)
#define		REG_EFUSE_MATCH_KEY			(EFUSE_REG_BASE + 0x0008)
#define		REG_EFUSE_TIMING0			(EFUSE_REG_BASE + 0x000C)
#define		REG_EFUSE_TIMING1			(EFUSE_REG_BASE + 0x0010)
#define		REG_EFUSE_TIMING2			(EFUSE_REG_BASE + 0x0014)
#define		REG_EFUSE_TIMING3			(EFUSE_REG_BASE + 0x0018)
#define		REG_EFUSE_TIMING4			(EFUSE_REG_BASE + 0x001C)
#define		REG_EFUSE_TIMING5			(EFUSE_REG_BASE + 0x0020)
#define		REG_EFUSE_TIMING6			(EFUSE_REG_BASE + 0x0024)
#define		REG_EFUSE_DOUT				(EFUSE_REG_BASE + 0x0028)
#define		REG_EFUSE_STATUS0			(EFUSE_REG_BASE + 0x002C)
#define		REG_EFUSE_STATUS1			(EFUSE_REG_BASE + 0x0030)
#define		REG_EFUSE_STATUS2			(EFUSE_REG_BASE + 0x0034)
#define		REG_EFUSE_STATUS3			(EFUSE_REG_BASE + 0x0038)
#define		REG_EFUSE_STATUS4			(EFUSE_REG_BASE + 0x003C)
#define		REG_EFUSE_MEM_INFO			(EFUSE_REG_BASE + 0x0100)

#define 	GPIO_SWPORTA_DR_OFFSET			(0x0)
#define 	GPIO_SWPORTA_DDR_OFFSET			(0x4)
#define 	GPIO_PORTA_CTL_OFFSET			(0x8)
#define 	GPIO_INTEN_OFFSET				(0x30)
#define 	GPIO_INTMASK_OFFSET				(0x34)
#define 	GPIO_INTTYPE_LEVEL_OFFSET		(0x38)
#define 	GPIO_INT_POLARITY_OFFSET		(0x3c)
#define 	GPIO_INTSTATUS_OFFSET			(0x40)
#define 	GPIO_RAWINTSTATUS_OFFSET		(0x44)
#define 	GPIO_DEBOUNCE_OFFSET			(0x48)
#define 	GPIO_PORTA_EOI_OFFSET			(0x4c)
#define 	GPIO_EXT_PORTA_OFFSET			(0x50)

#define 	GPIO_INTERVAL                			0x3d00000

#define		REG_GPIO_SWPORTA_DR(n)			  (GPIO_REG_BASE + ((n) * GPIO_INTERVAL) + GPIO_SWPORTA_DR_OFFSET)
#define		REG_GPIO_SWPORTA_DDR(n)			  (GPIO_REG_BASE + ((n) * GPIO_INTERVAL) + GPIO_SWPORTA_DDR_OFFSET)
#define		REG_GPIO_PORTA_CTL(n)			  (GPIO_REG_BASE + ((n) * GPIO_INTERVAL) + GPIO_PORTA_CTL_OFFSET)
#define		REG_GPIO_INTEN(n)				  (GPIO_REG_BASE + ((n) * GPIO_INTERVAL) + GPIO_INTEN_OFFSET)
#define		REG_GPIO_INTMASK(n)			 	  (GPIO_REG_BASE + ((n) * GPIO_INTERVAL) + GPIO_INTMASK_OFFSET)
#define		REG_GPIO_INTTYPE_LEVEL(n)		  (GPIO_REG_BASE + ((n) * GPIO_INTERVAL) + GPIO_INTTYPE_LEVEL_OFFSET)
#define		REG_GPIO_INT_POLARITY(n)		  (GPIO_REG_BASE + ((n) * GPIO_INTERVAL) + GPIO_INT_POLARITY_OFFSET)
#define		REG_GPIO_INTSTATUS(n)			  (GPIO_REG_BASE + ((n) * GPIO_INTERVAL) + GPIO_INTSTATUS_OFFSET)
#define		REG_GPIO_RAWINTSTATUS(n)		  (GPIO_REG_BASE + ((n) * GPIO_INTERVAL) + GPIO_RAWINTSTATUS_OFFSET)
#define		REG_GPIO_DEBOUNCE(n)			  (GPIO_REG_BASE + ((n) * GPIO_INTERVAL) + GPIO_DEBOUNCE_OFFSET)
#define		REG_GPIO_PORTA_EOI(n)			  (GPIO_REG_BASE + ((n) * GPIO_INTERVAL) + GPIO_PORTA_EOI_OFFSET)
#define		REG_GPIO_EXT_PORTA(n)			  (GPIO_REG_BASE + ((n) * GPIO_INTERVAL) + GPIO_EXT_PORTA_OFFSET)



//UART
#define     REG_UART_RBR         	(0x0000)
#define     REG_UART_THR         	(0x0000)
#define     REG_UART_DLL         	(0x0000)
#define     REG_UART_DLH         	(0x0004)
#define     REG_UART_IER         	(0x0004)
#define     REG_UART_IIR         	(0x0008)
#define     REG_UART_FCR         	(0x0008)
#define     REG_UART_LCR         	(0x000c)
#define     REG_UART_MCR         	(0x0010)
#define     REG_UART_LSR         	(0x0014)
#define     REG_UART_MSR         	(0x0018)
#define     REG_UART_SCR         	(0x001c)
#define     REG_UART_FAR         	(0x0070)
#define     REG_UART_TFR         	(0x0074)
#define     REG_UART_RFW         	(0x0078)
#define     REG_UART_USR         	(0x007c)
#define     REG_UART_TFL         	(0x0080)
#define     REG_UART_RFL         	(0x0084)
#define     REG_UART_SRR         	(0x0088)
#define     REG_UART_SFE         	(0x0098)
#define     REG_UART_SRT         	(0x009c)
#define     REG_UART_STET        	(0x00a0)
#define     REG_UART_HTX         	(0x00a4)
#define     REG_UART_DMASA			(0x00a8)
#define     REG_UART_CPR         	(0x00f4)
#define     REG_UART_UCV         	(0x00f8)
#define     REG_UART_CTR         	(0x00fc)




//SPI0
//SPI1
//SPI2
#define SPI_CTRL0_OFFSET            			(0x00)
#define SPI_CTRL1_OFFSET            			(0x04)
#define SPI_SSIENR_OFFSET               		(0x08)
#define SPI_MWCR_OFFSET             			(0x0c)
#define SPI_SER_OFFSET              			(0x10)
#define SPI_BAUD_OFFSET             			(0x14)
#define SPI_TXFTL_OFFSET            			(0x18)
#define SPI_RXFTL_OFFSET            			(0x1c)
#define SPI_TXFL_OFFSET             			(0x20)
#define SPI_RXFL_OFFSET             			(0x24)
#define SPI_STATUS_OFFSET               		(0x28)
#define SPI_IMR_OFFSET              			(0x2c)
#define SPI_ISR_OFFSET              			(0x30)
#define SPI_RISR_OFFSET             			(0x34)
#define SPI_TXOIC_OFFSET            			(0x38)
#define SPI_RXOIC_OFFSET            			(0x3c)
#define SPI_RXUIC_OFFSET            			(0x40)
#define SPI_MSTIC_OFFSET            			(0x44)
#define SPI_INTCLR_OFFSET               		(0x48)
#define SPI_DMACTRL_OFFSET              		(0x4c)
#define SPI_DMATDL_OFFSET               		(0x50)
#define SPI_DMARDL_OFFSET               		(0x54)
#define SPI_IDR_OFFSET              			(0x58)
#define SPI_SSI_COMPVER_OFFSET              	(0x5c)
#define SPI_DATA_OFFSET             			(0x60)
#define SPI_SAMPLE_DELAY             			(0xf0)
//spic new add reg.
#define SPI_CCFGR_OFFSET             		(0xf4)
#define SPI_OPCR_OFFSET             		(0xf8)
#define SPI_TIMCR_OFFSET             		(0xfc)
#define SPI_BBAR0_OFFSET             		(0x100)
#define SPI_BBAR1_OFFSET             		(0x104)

#define SPI_INTERVAL                			0x100000

#define     REG_SPI_CTRLR0                   (SPI0_REG_BASE + SPI_CTRL0_OFFSET)
                                                			/*  0:3  DFS : Data Frame Size
                                        						4:5  FRF : Frame Format
                                                				6    SCPH : Serial Clock PHase
                                            					7    SCPOL: Serial POLarity
                                            					8:9  TMOD : Transfer MODe
                                                				10   SLV_OE: SLaVe Output Enable
                                                    			11   SRL : Shift Register Loop
                                                        		12:15   CFS : Control Frame Size 		*/
#define     REG_SPI_CTRLR1                   (SPI0_REG_BASE + SPI_CTRL1_OFFSET)
                                                            /* only for dw_apb_ssi is configured as a master and
                                                             * set the number of data frames to be received
                                        					   by the dw_apb_ssi */
#define     REG_SPI_SSIENR                   (SPI0_REG_BASE + SPI_SSIENR_OFFSET)
                                                            /* ENable and disable all dw_apb_SSI operations .  SSI ENable*/
#define     REG_SPI_MWCR                     (SPI0_REG_BASE  + SPI_MWCR_OFFSET)
#define     REG_SPI_SER                      (SPI0_REG_BASE  + SPI_SER_OFFSET)
                                                            /* Slave Enable Register ,select slave select line
                                                			 * to communication the slave  */
#define     REG_SPI_BAUDR                    (SPI0_REG_BASE  + SPI_BAUD_OFFSET)
                                                            /* only for dw_aph_ssi is configured as a master ,
                                                             * enables the individual slave select output lines from dw_apb_ssi master */
#define     REG_SPI_TXFTLR                   (SPI0_REG_BASE  + SPI_TXFTL_OFFSET)
                                                            /* control the threshold value for the transmit  FIFO memory */
#define     REG_SPI_RXFTLR                   (SPI0_REG_BASE  + SPI_RXFTL_OFFSET)
                                                            /* Receive fifo Overflow Interrupt Clear Register */
#define     REG_SPI_TXFLR                    (SPI0_REG_BASE  + SPI_TXFL_OFFSET)
                                                            /* contains the number of valid data entries */
#define     REG_SPI_RXFLR                    (SPI0_REG_BASE  + SPI_RXFL_OFFSET)
#define     REG_SPI_SR                       (SPI0_REG_BASE  + SPI_STATUS_OFFSET)
#define     REG_SPI_IMR                      (SPI0_REG_BASE  + SPI_IMR_OFFSET)
#define     REG_SPI_ISR                      (SPI0_REG_BASE  + SPI_ISR_OFFSET)
#define     REG_SPI_RISR                     (SPI0_REG_BASE  + SPI_RISR_OFFSET)
#define     REG_SPI_TXOICR                   (SPI0_REG_BASE  + SPI_TXOIC_OFFSET)
#define     REG_SPI_RXOICR                   (SPI0_REG_BASE  + SPI_RXOIC_OFFSET)
#define     REG_SPI_RXUICR                   (SPI0_REG_BASE  + SPI_RXUIC_OFFSET)
#define     REG_SPI_MSTICR                   (SPI0_REG_BASE  + SPI_MSTIC_OFFSET)
#define     REG_SPI_ICR                      (SPI0_REG_BASE  + SPI_INTCLR_OFFSET)
#define     REG_SPI_DMACR                    (SPI0_REG_BASE  + SPI_DMACTRL_OFFSET)
#define     REG_SPI_DMATDLR                  (SPI0_REG_BASE  + SPI_DMATDL_OFFSET)
#define     REG_SPI_DMARDLR                  (SPI0_REG_BASE  + SPI_DMARDL_OFFSET)
#define     REG_SPI_IDR                      (SPI0_REG_BASE  + SPI_IDR_OFFSET)
#define     REG_SPI_SSI_COMP_VERSION         (SPI0_REG_BASE  + SPI_SSI_COMPVER_OFFSET)
#define     REG_SPI_SSI_DR                   (SPI0_REG_BASE  + SPI_DATA_OFFSET)
#define		REG_SPI_SSI_SAMPLE_DELAY         (SPI0_REG_BASE  + SPI_SAMPLE_DELAY)
//spic new add reg.
#define REG_SPI_CCFGR        	    (SPI0_REG_BASE  + SPI_CCFGR_OFFSET)
#define REG_SPI_OPCR			    (SPI0_REG_BASE  + SPI_OPCR_OFFSET)
#define REG_SPI_TIMCR        	    (SPI0_REG_BASE  + SPI_TIMCR_OFFSET)
#define REG_SPI_BBAR0        	    (SPI0_REG_BASE  + SPI_BBAR0_OFFSET)
#define REG_SPI_BBAR1        	    (SPI0_REG_BASE  + SPI_BBAR1_OFFSET)

// SCU Register
#define REG_PMU_CHIP_ID                  (PMU_REG_BASE + 0x0000)
#define REG_PMU_ECO_PACKAGE_ID           (PMU_REG_BASE + 0x0004)
#define REG_PMU_FW_VER                   (PMU_REG_BASE + 0x0008)
#define REG_PMU_CLK_SEL                  (PMU_REG_BASE + 0x000c)
#define REG_PMU_PLL0_CTRL0               (PMU_REG_BASE + 0x0010)
#define REG_PMU_PLL1_CTRL0               (PMU_REG_BASE + 0x0014)
#define REG_PMU_PLL0_CTRL1               (PMU_REG_BASE + 0x0018)
#define REG_PMU_CLK_GATE0                (PMU_REG_BASE + 0x001c)
#define REG_PMU_CLK_GATE1                (PMU_REG_BASE + 0x0020)
#define REG_PMU_CLK_DIV0                 (PMU_REG_BASE + 0x0024)
#define REG_PMU_CLK_DIV1                 (PMU_REG_BASE + 0x0028)
#define REG_PMU_CLK_DIV2                 (PMU_REG_BASE + 0x002c)
#define REG_PMU_CLK_DIV3                 (PMU_REG_BASE + 0x0030)
#define REG_PMU_CLK_DIV4                 (PMU_REG_BASE + 0x0034)
#define REG_PMU_CLK_DIV5                 (PMU_REG_BASE + 0x0038)
#define REG_PMU_CLK_DIV6                 (PMU_REG_BASE + 0x003c)
#define REG_PMU_SWRST_MAIN_CTRL          (PMU_REG_BASE + 0x0040)
#define REG_PMU_SWRST_MAIN_CTRL2         (PMU_REG_BASE + 0x0044)
#define REG_PMU_SWRST_AHB_CTRL           (PMU_REG_BASE + 0x0048)
#define REG_PMU_SWRST_APB_CTRL           (PMU_REG_BASE + 0x004c)
#define REG_PMU_SPC_IO_STATUS            (PMU_REG_BASE + 0x0054)
#define REG_PMU_SPC_FUN                  (PMU_REG_BASE + 0x0058)
#define REG_PMU_CLK_DIV7                 (PMU_REG_BASE + 0x005c)
#define REG_PMU_CLK_DIV8                 (PMU_REG_BASE + 0x0060)
#define REG_PMU_PLL2_CTRL0               (PMU_REG_BASE + 0x0064)
#define REG_PMU_PLL2_CTRL1               (PMU_REG_BASE + 0x0068)
#define REG_PMU_PLL1_CTRL1               (PMU_REG_BASE + 0x006c)
#define REG_PMU_PAD_POWER_SEL            (PMU_REG_BASE + 0x0074)
#define REG_PMU_SWRSTN_NSR               (PMU_REG_BASE + 0x0078)
#define REG_PMU_SWRST_NSR1               (PMU_REG_BASE + 0x007c)



// PMU Registers
#define REG_PMU_PAD_BOOT_MODE_CFG        (PMU_REG_BASE + 0x0080)
#define REG_PMU_PAD_BOOT_SEL1_CFG        (PMU_REG_BASE + 0x0084)
#define REG_PMU_PAD_BOOT_SEL0_CFG        (PMU_REG_BASE + 0x0088)
#define REG_PMU_PAD_UART0_TX_CFG         (PMU_REG_BASE + 0x008c)
#define REG_PMU_PAD_UART0_RX_CFG         (PMU_REG_BASE + 0x0090)
#define REG_PMU_PAD_I2C0_SCL_CFG         (PMU_REG_BASE + 0x0094)
#define REG_PMU_PAD_I2C0_SDA_CFG         (PMU_REG_BASE + 0x0098)
#define REG_PMU_PAD_SENSOR_CLK_CFG       (PMU_REG_BASE + 0x009c)
#define REG_PMU_PAD_SENSOR_RSTN_CFG      (PMU_REG_BASE + 0x00a0)
#define REG_PMU_PAD_UART1_TX_CFG         (PMU_REG_BASE + 0x00a4)
#define REG_PMU_PAD_UART1_RX_CFG         (PMU_REG_BASE + 0x00a8)
#define REG_PMU_PAD_I2C1_SCL_CFG         (PMU_REG_BASE + 0x00ac)
#define REG_PMU_PAD_I2C1_SDA_CFG         (PMU_REG_BASE + 0x00b0)
#define REG_PMU_PAD_UART2_TX_CFG         (PMU_REG_BASE + 0x00b4)
#define REG_PMU_PAD_UART2_RX_CFG         (PMU_REG_BASE + 0x00b8)
#define REG_PMU_PAD_USB_PWREN_CFG        (PMU_REG_BASE + 0x00bc)
#define REG_PMU_PAD_PWM0_CFG             (PMU_REG_BASE + 0x00c0)
#define REG_PMU_PAD_PWM1_CFG             (PMU_REG_BASE + 0x00c4)
#define REG_PMU_PAD_PWM2_CFG             (PMU_REG_BASE + 0x00c8)
#define REG_PMU_PAD_PWM3_CFG             (PMU_REG_BASE + 0x00cc)
#define REG_PMU_PAD_MAC_RMII_CLK_CFG     (PMU_REG_BASE + 0x00d0)
#define REG_PMU_PAD_MAC_REF_CLK_CFG      (PMU_REG_BASE + 0x00d4)
#define REG_PMU_PAD_MAC_TXD0_CFG         (PMU_REG_BASE + 0x00d8)
#define REG_PMU_PAD_MAC_TXD1_CFG         (PMU_REG_BASE + 0x00dc)
#define REG_PMU_PAD_MAC_TXEN_CFG         (PMU_REG_BASE + 0x00e0)
#define REG_PMU_PAD_MAC_RXD0_CFG         (PMU_REG_BASE + 0x00e4)
#define REG_PMU_PAD_MAC_RXD1_CFG         (PMU_REG_BASE + 0x00e8)
#define REG_PMU_PAD_MAC_RXDV_CFG         (PMU_REG_BASE + 0x00ec)
#define REG_PMU_PAD_MAC_MDC_CFG          (PMU_REG_BASE + 0x00f0)
#define REG_PMU_PAD_MAC_MDIO_CFG         (PMU_REG_BASE + 0x00f4)
#define REG_PMU_PAD_SD1_CLK_CFG          (PMU_REG_BASE + 0x00f8)
#define REG_PMU_PAD_SD1_CD_CFG           (PMU_REG_BASE + 0x00fc)
#define REG_PMU_PAD_SD1_CMD_RSP_CFG      (PMU_REG_BASE + 0x0100)
#define REG_PMU_PAD_SD1_DATA_0_CFG       (PMU_REG_BASE + 0x0104)
#define REG_PMU_PAD_SD1_DATA_1_CFG       (PMU_REG_BASE + 0x0108)
#define REG_PMU_PAD_SD1_DATA_2_CFG       (PMU_REG_BASE + 0x010c)
#define REG_PMU_PAD_SD1_DATA_3_CFG       (PMU_REG_BASE + 0x0110)
#define REG_PMU_PAD_GPIO_0_CFG           (PMU_REG_BASE + 0x0114)
#define REG_PMU_PAD_GPIO_1_CFG           (PMU_REG_BASE + 0x0118)
#define REG_PMU_PAD_GPIO_2_CFG           (PMU_REG_BASE + 0x011c)
#define REG_PMU_PAD_GPIO_3_CFG           (PMU_REG_BASE + 0x0120)
#define REG_PMU_PAD_GPIO_4_CFG           (PMU_REG_BASE + 0x0124)
#define REG_PMU_PAD_SSI0_CLK_CFG         (PMU_REG_BASE + 0x0128)
#define REG_PMU_PAD_SSI0_CSN_0_CFG       (PMU_REG_BASE + 0x012c)
#define REG_PMU_PAD_SSI0_TXD_CFG         (PMU_REG_BASE + 0x0130)
#define REG_PMU_PAD_SSI0_RXD_CFG         (PMU_REG_BASE + 0x0134)
#define REG_PMU_PAD_SSI0_D2_CFG          (PMU_REG_BASE + 0x0138)
#define REG_PMU_PAD_SSI0_D3_CFG          (PMU_REG_BASE + 0x013c)
#define REG_PMU_PAD_SSI1_CLK_CFG         (PMU_REG_BASE + 0x0140)
#define REG_PMU_PAD_SSI1_CSN_0_CFG       (PMU_REG_BASE + 0x0144)
#define REG_PMU_PAD_SSI1_TXD_CFG         (PMU_REG_BASE + 0x0148)
#define REG_PMU_PAD_SSI1_RXD_CFG         (PMU_REG_BASE + 0x014c)
#define REG_PMU_PAD_SD0_CD_CFG           (PMU_REG_BASE + 0x0150)
#define REG_PMU_PAD_SD0_CLK_CFG          (PMU_REG_BASE + 0x0154)
#define REG_PMU_PAD_SD0_CMD_RSP_CFG      (PMU_REG_BASE + 0x0158)
#define REG_PMU_PAD_SD0_DATA_0_CFG       (PMU_REG_BASE + 0x015c)
#define REG_PMU_PAD_SD0_DATA_1_CFG       (PMU_REG_BASE + 0x0160)
#define REG_PMU_PAD_SD0_DATA_2_CFG       (PMU_REG_BASE + 0x0164)
#define REG_PMU_PAD_SD0_DATA_3_CFG       (PMU_REG_BASE + 0x0168)
#define REG_PMU_PAD_SADC_XAIN0_CFG       (PMU_REG_BASE + 0x016c)
#define REG_PMU_PAD_SADC_XAIN1_CFG       (PMU_REG_BASE + 0x0170)
#define REG_PMU_PAD_SADC_XAIN2_CFG       (PMU_REG_BASE + 0x0174)
#define REG_PMU_PAD_SADC_XAIN3_CFG       (PMU_REG_BASE + 0x0178)
#define REG_PMU_PAD_GPIO_28_CFG          (PMU_REG_BASE + 0x017c)
#define REG_PMU_PAD_GPIO_29_CFG          (PMU_REG_BASE + 0x0180)
#define REG_PMU_ARM_INT_MASK             (PMU_REG_BASE + 0x01e0)
#define REG_PMU_ARM_INT_RAWSTAT          (PMU_REG_BASE + 0x01e4)
#define REG_PMU_ARM_INT_STAT             (PMU_REG_BASE + 0x01e8)
#define REG_PMU_A625_INT_MASK            (PMU_REG_BASE + 0x01ec)
#define REG_PMU_A625_INT_RAWSTAT         (PMU_REG_BASE + 0x01f0)
#define REG_PMU_A625_INT_STAT            (PMU_REG_BASE + 0x01f4)
#define REG_PMU_DMA_SEL                  (PMU_REG_BASE + 0x01f8)
#define REG_PMU_WDT_CTRL                 (PMU_REG_BASE + 0x01fc)
#define REG_PMU_DBG_STAT0                (PMU_REG_BASE + 0x0200)
#define REG_PMU_DBG_STAT1                (PMU_REG_BASE + 0x0204)
#define REG_PMU_USB_CFG                  (PMU_REG_BASE + 0x214)
#define REG_PMU_USB_SYS0                 (PMU_REG_BASE + 0x210)
#define REG_PMU_USB_SYS1                 (PMU_REG_BASE + 0x228)
#define REG_PMU_USB_TUNE                 (PMU_REG_BASE + 0x218)
#define REG_PMU_SYNOP_TESTPORT           (PMU_REG_BASE + 0x0224)
#define REG_PMU_PTSLO                    (PMU_REG_BASE + 0x022c)
#define REG_PMU_PTSHI                    (PMU_REG_BASE + 0x0230)
#define REG_PMU_USER0                (PMU_REG_BASE + 0x0234)
#define REG_PMU_HPROT_CTRL               (PMU_REG_BASE + 0x0238)
#define REG_PMU_QOS_CTRL0                (PMU_REG_BASE + 0x023c)
#define REG_PMU_QOS_CTRL1                (PMU_REG_BASE + 0x0240)
#define REG_PMU_LPC_CTRL0                (PMU_REG_BASE + 0x0300)
#define REG_PMU_LPC_CTRL1                (PMU_REG_BASE + 0x0304)
#define REG_PMU_LPC_CTRL2                (PMU_REG_BASE + 0x0308)
#define REG_PMU_LPC_CTRL3                (PMU_REG_BASE + 0x030c)
#define REG_PMU_LPC_CTRL4                (PMU_REG_BASE + 0x0320)
#define REG_PMU_LPC_CTRL5                (PMU_REG_BASE + 0x0324)
#define REG_PMU_LPC_CTRL6                (PMU_REG_BASE + 0x0328)

#define REG_PMU_WREN                (PMU_REG_BASE + 0x032C)
#define REG_PMU_RESERVED0           (PMU_REG_BASE + 0x0330)
#define REG_PMU_RESERVED1           (PMU_REG_BASE + 0x0334)
#define REG_PMU_RESERVED2           (PMU_REG_BASE + 0x0338)
#define REG_PMU_RESERVED3           (PMU_REG_BASE + 0x033c)
#define REG_PMU_RESERVED4           (PMU_REG_BASE + 0x0340)
#define REG_PMU_RESERVED5           (PMU_REG_BASE + 0x0344)
#define REG_PMU_RESERVED6           (PMU_REG_BASE + 0x0348)
#define REG_PMU_RESERVED7           (PMU_REG_BASE + 0x034c)
#define REG_PMU_RESERVED8           (PMU_REG_BASE + 0x0350)
#define REG_PMU_RESERVED9           (PMU_REG_BASE + 0x0354)
#define REG_PMU_RESERVED10           (PMU_REG_BASE + 0x0358)
#define REG_PMU_RESERVED11           (PMU_REG_BASE + 0x035c)
#define REG_PMU_RESERVED12           (PMU_REG_BASE + 0x0360)
#define REG_PMU_RESERVED13           (PMU_REG_BASE + 0x0364)
#define REG_PMU_RESERVED14           (PMU_REG_BASE + 0x0368)
#define REG_PMU_RESERVED15           (PMU_REG_BASE + 0x036c)
#define REG_PMU_EPHY_PARAM              (REG_PMU_RESERVED4)
#define REG_PMU_RTC_PARAM               (REG_PMU_RESERVED5)

#define REG_PMU_SD1_FUNC_SEL	    (PMU_REG_BASE + 0x03a0)
#define REG_PMU_PRDCID_CTRL0             (PMU_REG_BASE + 0x0500)
#define REG_PMU_PRDCID_CTRL1             (PMU_REG_BASE + 0x0504)
#define REG_PMU_A625BOOT0                (PMU_REG_BASE + 0x2000)
#define REG_PMU_A625BOOT1                (PMU_REG_BASE + 0x2004)
#define REG_PMU_A625BOOT2                (PMU_REG_BASE + 0x2008)
#define REG_PMU_A625BOOT3                (PMU_REG_BASE + 0x200c)
#define REG_PMU_A625_START_CTRL          (PMU_REG_BASE + 0x2010)
#define REG_PMU_ARC_INTC_MASK            (PMU_REG_BASE + 0x2014)
#define REG_PMU_PERF_MONI_REG0           (PMU_REG_BASE + 0x2018)
#define REG_PMU_PERF_MONI_REG1           (PMU_REG_BASE + 0x201c)
#define REG_PMU_PERF_MONI_REG2           (PMU_REG_BASE + 0x2020)
#define REG_PMU_PERF_MONI_REG3           (PMU_REG_BASE + 0x2024)
#define REG_PMU_PERF_MONI_REG4           (PMU_REG_BASE + 0x2028)
#define REG_PMU_PERF_MONI_REG5           (PMU_REG_BASE + 0x202c)
#define REG_PMU_PERF_MONI_REG6           (PMU_REG_BASE + 0x2030)
#define REG_PMU_PERF_MONI_REG7           (PMU_REG_BASE + 0x2034)
#define REG_PMU_PERF_MONI_REG8           (PMU_REG_BASE + 0x2038)
#define REG_PMU_PERF_MONI_REG9           (PMU_REG_BASE + 0x203c)
#define REG_PMU_PERF_MONI_REG10          (PMU_REG_BASE + 0x2040)
#define REG_PMU_PERF_MONI_REG11          (PMU_REG_BASE + 0x2044)
#define REG_PMU_PERF_MONI_REG12          (PMU_REG_BASE + 0x2048)
#define REG_PMU_PERF_MONI_REG13          (PMU_REG_BASE + 0x204c)
#define REG_PMU_PERF_MONI_REG14          (PMU_REG_BASE + 0x2050)
#define REG_PMU_PERF_MONI_REG15          (PMU_REG_BASE + 0x2054)
#define REG_PMU_PERF_MONI_REG16          (PMU_REG_BASE + 0x2058)
#define REG_PMU_PERF_MONI_REG17          (PMU_REG_BASE + 0x205c)
#define REG_PMU_PERF_MONI_REG18          (PMU_REG_BASE + 0x2060)
#define REG_PMU_PERF_MONI_REG19          (PMU_REG_BASE + 0x2064)
#define REG_PMU_PERF_MONI_REG20          (PMU_REG_BASE + 0x2068)
#define REG_PMU_PERF_MONI_REG21          (PMU_REG_BASE + 0x206c)
#define REG_PMU_PERF_MONI_REG22          (PMU_REG_BASE + 0x2070)
#define REG_PMU_PERF_MONI_REG23          (PMU_REG_BASE + 0x2074)
#define REG_PMU_PERF_MONI_REG24          (PMU_REG_BASE + 0x2078)
#define REG_PMU_PERF_MONI_REG25          (PMU_REG_BASE + 0x207c)
#define REG_PMU_PERF_MONI_REG26          (PMU_REG_BASE + 0x2080)
#define REG_PMU_PERF_MONI_REG27          (PMU_REG_BASE + 0x2084)
#define REG_PMU_PERF_MONI_REG28          (PMU_REG_BASE + 0x2088)
#define REG_PMU_PERF_MONI_REG29          (PMU_REG_BASE + 0x208c)
#define REG_PMU_PERF_MONI_REG30          (PMU_REG_BASE + 0x2090)
#define REG_PMU_PERF_MONI_REG31          (PMU_REG_BASE + 0x2094)
#define REG_PMU_PERF_MONI_REG32          (PMU_REG_BASE + 0x2098)
#define REG_PMU_PERF_MONI_REG33          (PMU_REG_BASE + 0x209c)
#define REG_PMU_PERF_MONI_REG34          (PMU_REG_BASE + 0x20a0)
#define REG_PMU_PERF_MONI_REG35          (PMU_REG_BASE + 0x20a4)
#define REG_PMU_PERF_MONI_REG36          (PMU_REG_BASE + 0x20a8)
#define REG_PMU_PERF_MONI_REG37          (PMU_REG_BASE + 0x20ac)
#define REG_PMU_PERF_MONI_REG38          (PMU_REG_BASE + 0x20b0)
#define REG_PMU_PERF_MONI_REG39          (PMU_REG_BASE + 0x20b4)
#define REG_PMU_PERF_MONI_REG40          (PMU_REG_BASE + 0x20b8)
#define REG_PMU_PERF_MONI_REG41          (PMU_REG_BASE + 0x20bc)
#define REG_PMU_PERF_MONI_REG42          (PMU_REG_BASE + 0x20c0)
#define REG_PMU_PERF_MONI_REG43          (PMU_REG_BASE + 0x20c4)
#define REG_PMU_PERF_MONI_REG44          (PMU_REG_BASE + 0x20c8)
#define REG_PMU_PERF_MONI_REG45          (PMU_REG_BASE + 0x20cc)
#define REG_PMU_PERF_MONI_REG46          (PMU_REG_BASE + 0x20d0)
#define REG_PMU_PERF_MONI_REG47          (PMU_REG_BASE + 0x20d4)
#define REG_PMU_PERF_MONI_REG48          (PMU_REG_BASE + 0x20d8)
#define REG_PMU_PERF_MONI_REG49          (PMU_REG_BASE + 0x20dc)
#define REG_PMU_PERF_MONI_REG50          (PMU_REG_BASE + 0x20e0)
#define REG_PMU_PERF_MONI_REG51          (PMU_REG_BASE + 0x20e4)
#define REG_PMU_PERF_MONI_REG52          (PMU_REG_BASE + 0x20e8)
#define REG_PMU_PERF_MONI_REG53          (PMU_REG_BASE + 0x20ec)
#define REG_PMU_PERF_MONI_REG54          (PMU_REG_BASE + 0x20f0)
#define REG_PMU_PERF_MONI_REG55          (PMU_REG_BASE + 0x20f4)
#define REG_PMU_PERF_MONI_REG56          (PMU_REG_BASE + 0x20f8)
#define REG_PMU_PERF_MONI_REG57          (PMU_REG_BASE + 0x20fc)
#define REG_PMU_PERF_MONI_REG58          (PMU_REG_BASE + 0x2100)
#define REG_PMU_PERF_MONI_REG59          (PMU_REG_BASE + 0x2104)
#define REG_PMU_EFHY_REG0                (PMU_REG_BASE + 0x2108)
#define REG_PMU_EFHY_REG1                (PMU_REG_BASE + 0x210c)
#define REG_PMU_SCU_PLL_WREN		 (PMU_REG_BASE + 0x2110)
/* Public function ----------------------------------------------------------*/


/* gmac para */

#define GMAC_SPEED_SWITCH_PMU_REG_OFFSET       (PMU_REG_BASE + 0x0c)
#define GMAC_SPEED_SWITCH_BIT_POS      24
#define GMAC_SPEED_SWITCH_100M_VAL     0x01
#define GMAC_REG_BASE                  (0xE0600000)

#define PMU_GMAC_SPEED_MODE_POS          (24)
#define PMU_GMAC_BUS_RESET_POS           (17)
#define PMU_MAC_RXDV_GPIO_MUX_INDEX      (1)

#define PMU_RMII_SPEED_MODE (REG_PMU_CLK_SEL)
#define FH_GMAC_AHB_RESET                                      (1<<17)
#define FH_GMAC_SPEED_100M                                     (1<<24)
#define FH_GMAC_RMII_CLK_MODE                          (1<<27)

/* inside fhy below */
#define CLK_SCAN_BIT_POS                (28)
#define INSIDE_PHY_ENABLE_BIT_POS       (24)
#define MAC_REF_CLK_DIV_MASK            (0x0f)
#define MAC_REF_CLK_DIV_BIT_POS         (24)
#define MAC_PAD_RMII_CLK_MASK           (0x0f)
#define MAC_PAD_RMII_CLK_BIT_POS        (24)
#define MAC_PAD_MAC_REF_CLK_BIT_POS     (28)
#define ETH_REF_CLK_OUT_GATE_BIT_POS    (25)
#define ETH_RMII_CLK_OUT_GATE_BIT_POS   (28)
#define IN_OR_OUT_PHY_SEL_BIT_POS       (26)
#define INSIDE_CLK_GATE_BIT_POS         (0)
#define INSIDE_PHY_SHUTDOWN_BIT_POS     (31)
#define INSIDE_PHY_RST_BIT_POS          (30)
#define INSIDE_PHY_TRAINING_BIT_POS     (27)
#define INSIDE_PHY_TRAINING_MASK        (0x0f)


#define REG_PMU_BOOTMODE_SW (REG_PMU_RESERVED0)
#endif
