#ifndef __chn_yuv_type_h__
#define __chn_yuv_type_h__

/*说明; 此文件的目的是定义这三个宏,CH0_YUV_TYPE, CH1_YUV_TYPE, CH2_YUV_TYPE*/

#ifdef VIDEO_GRP0

#if !defined(CONFIG_ARCH_FH8626V100) && !defined(CONFIG_ARCH_FH8636)
#ifdef FH_CH0_USING_SCAN_G0
#define CH0_YUV_TYPE_G0 VPU_VOMODE_SCAN
#endif

#ifdef FH_CH0_USING_BLK_G0
#define CH0_YUV_TYPE_G0 VPU_VOMODE_BLK
#endif

#ifdef FH_CH0_USING_TILE192_G0
#define CH0_YUV_TYPE_G0 VPU_VOMODE_TILE192
#endif

#ifdef FH_CH0_USING_TILE224_G0
#define CH0_YUV_TYPE_G0 VPU_VOMODE_TILE224
#endif

#ifdef FH_CH0_USING_TILE256_G0
#define CH0_YUV_TYPE_G0 VPU_VOMODE_TILE256
#endif

#ifdef FH_CH0_USING_TILE256_G0
#define CH0_YUV_TYPE_G0 VPU_VOMODE_TILE256
#endif

#ifdef FH_CH0_USING_YUYV_G0
#define CH0_YUV_TYPE_G0 VPU_VOMODE_YUYV
#endif

#ifdef FH_CH0_USING_NV16_G0
#define CH0_YUV_TYPE_G0 VPU_VOMODE_NV16
#endif

#ifndef CH0_YUV_TYPE_G0
#define CH0_YUV_TYPE_G0 VPU_VOMODE_BLK
#endif

#ifdef FH_CH1_USING_SCAN_G0
#define CH1_YUV_TYPE_G0 VPU_VOMODE_SCAN
#endif

#ifdef FH_CH1_USING_BLK_G0
#define CH1_YUV_TYPE_G0 VPU_VOMODE_BLK
#endif

#ifdef FH_CH1_USING_TILE192_G0
#define CH1_YUV_TYPE_G0 VPU_VOMODE_TILE192
#endif

#ifdef FH_CH1_USING_TILE224_G0
#define CH1_YUV_TYPE_G0 VPU_VOMODE_TILE224
#endif

#ifdef FH_CH1_USING_TILE256_G0
#define CH1_YUV_TYPE_G0 VPU_VOMODE_TILE256
#endif

#ifdef FH_CH1_USING_YUYV_G0
#define CH1_YUV_TYPE_G0 VPU_VOMODE_YUYV
#endif

#ifdef FH_CH1_USING_NV16_G0
#define CH1_YUV_TYPE_G0 VPU_VOMODE_NV16
#endif

#ifndef CH1_YUV_TYPE_G0
#define CH1_YUV_TYPE_G0 VPU_VOMODE_BLK
#endif

#ifdef FH_CH2_USING_SCAN_G0
#define CH2_YUV_TYPE_G0 VPU_VOMODE_SCAN
#endif

#ifdef FH_CH2_USING_BLK_G0
#define CH2_YUV_TYPE_G0 VPU_VOMODE_BLK
#endif

#ifdef FH_CH2_USING_TILE192_G0
#define CH2_YUV_TYPE_G0 VPU_VOMODE_TILE192
#endif

#ifdef FH_CH2_USING_TILE224_G0
#define CH2_YUV_TYPE_G0 VPU_VOMODE_TILE224
#endif

#ifdef FH_CH2_USING_TILE256_G0
#define CH2_YUV_TYPE_G0 VPU_VOMODE_TILE256
#endif

#ifdef FH_CH2_USING_YUYV_G0
#define CH2_YUV_TYPE_G0 VPU_VOMODE_YUYV
#endif

#ifdef FH_CH2_USING_NV16_G0
#define CH2_YUV_TYPE_G0 VPU_VOMODE_NV16
#endif

#ifndef CH2_YUV_TYPE_G0
#define CH2_YUV_TYPE_G0 VPU_VOMODE_BLK
#endif

#ifdef FH_CH3_USING_SCAN_G0
#define CH3_YUV_TYPE_G0 VPU_VOMODE_SCAN
#endif

#ifdef FH_CH3_USING_NV16_G0
#define CH3_YUV_TYPE_G0 VPU_VOMODE_NV16
#endif

#ifdef FH_CH3_USING_RRGGBB_G0
#define CH3_YUV_TYPE_G0 VPU_VOMODE_RRGGBB
#endif

#ifdef FH_CH3_USING_RGB888_G0
#define CH3_YUV_TYPE_G0 VPU_VOMODE_RGB888
#endif

#else
#define CH0_YUV_TYPE_G0 VPU_VOMODE_SCAN
#define CH1_YUV_TYPE_G0 VPU_VOMODE_SCAN
#define CH2_YUV_TYPE_G0 VPU_VOMODE_SCAN
#define CH3_YUV_TYPE_G0 VPU_VOMODE_RGB888
#endif

#endif /* VIDEO_GRP0 */

#ifdef VIDEO_GRP1

#if !defined(CONFIG_ARCH_FH8626V100) && !defined(CONFIG_ARCH_FH8636)
#ifdef FH_CH0_USING_SCAN_G1
#define CH0_YUV_TYPE_G1 VPU_VOMODE_SCAN
#endif

#ifdef FH_CH0_USING_BLK_G1
#define CH0_YUV_TYPE_G1 VPU_VOMODE_BLK
#endif

#ifdef FH_CH0_USING_TILE192_G1
#define CH0_YUV_TYPE_G1 VPU_VOMODE_TILE192
#endif

#ifdef FH_CH0_USING_TILE224_G1
#define CH0_YUV_TYPE_G1 VPU_VOMODE_TILE224
#endif

#ifdef FH_CH0_USING_TILE256_G1
#define CH0_YUV_TYPE_G1 VPU_VOMODE_TILE256
#endif

#ifdef FH_CH0_USING_YUYV_G1
#define CH0_YUV_TYPE_G1 VPU_VOMODE_YUYV
#endif

#ifdef FH_CH0_USING_NV16_G1
#define CH0_YUV_TYPE_G1 VPU_VOMODE_NV16
#endif

#ifndef CH0_YUV_TYPE_G1
#define CH0_YUV_TYPE_G1 VPU_VOMODE_BLK
#endif

#ifdef FH_CH1_USING_SCAN_G1
#define CH1_YUV_TYPE_G1 VPU_VOMODE_SCAN
#endif

#ifdef FH_CH1_USING_BLK_G1
#define CH1_YUV_TYPE_G1 VPU_VOMODE_BLK
#endif

#ifdef FH_CH1_USING_TILE192_G1
#define CH1_YUV_TYPE_G1 VPU_VOMODE_TILE192
#endif

#ifdef FH_CH1_USING_TILE224_G1
#define CH1_YUV_TYPE_G1 VPU_VOMODE_TILE224
#endif

#ifdef FH_CH1_USING_TILE256_G1
#define CH1_YUV_TYPE_G1 VPU_VOMODE_TILE256
#endif

#ifdef FH_CH1_USING_YUYV_G1
#define CH1_YUV_TYPE_G1 VPU_VOMODE_YUYV
#endif

#ifdef FH_CH1_USING_NV16_G1
#define CH1_YUV_TYPE_G1 VPU_VOMODE_NV16
#endif

#ifndef CH1_YUV_TYPE_G1
#define CH1_YUV_TYPE_G1 VPU_VOMODE_BLK
#endif

#ifdef FH_CH2_USING_SCAN_G1
#define CH2_YUV_TYPE_G1 VPU_VOMODE_SCAN
#endif

#ifdef FH_CH2_USING_BLK_G1
#define CH2_YUV_TYPE_G1 VPU_VOMODE_BLK
#endif

#ifdef FH_CH2_USING_TILE192_G1
#define CH2_YUV_TYPE_G1 VPU_VOMODE_TILE192
#endif

#ifdef FH_CH2_USING_TILE224_G1
#define CH2_YUV_TYPE_G1 VPU_VOMODE_TILE224
#endif

#ifdef FH_CH2_USING_TILE256_G1
#define CH2_YUV_TYPE_G1 VPU_VOMODE_TILE256
#endif

#ifdef FH_CH2_USING_YUYV_G1
#define CH2_YUV_TYPE_G1 VPU_VOMODE_YUYV
#endif

#ifdef FH_CH2_USING_NV16_G1
#define CH2_YUV_TYPE_G1 VPU_VOMODE_NV16
#endif

#ifndef CH2_YUV_TYPE_G1
#define CH2_YUV_TYPE_G1 VPU_VOMODE_BLK
#endif

#ifdef FH_CH3_USING_SCAN_G1
#define CH3_YUV_TYPE_G1 VPU_VOMODE_SCAN
#endif

#ifdef FH_CH3_USING_NV16_G1
#define CH3_YUV_TYPE_G1 VPU_VOMODE_NV16
#endif

#ifdef FH_CH3_USING_RRGGBB_G1
#define CH3_YUV_TYPE_G1 VPU_VOMODE_RRGGBB
#endif

#ifdef FH_CH3_USING_RGB888_G1
#define CH3_YUV_TYPE_G1 VPU_VOMODE_RGB888
#endif

#else
#define CH0_YUV_TYPE_G1 VPU_VOMODE_SCAN
#define CH1_YUV_TYPE_G1 VPU_VOMODE_SCAN
#define CH2_YUV_TYPE_G1 VPU_VOMODE_SCAN
#define CH3_YUV_TYPE_G1 VPU_VOMODE_RGB888
#endif

#endif /* VIDEO_GRP1 */

#ifdef VIDEO_GRP2

#if !defined(CONFIG_ARCH_FH8626V100) && !defined(CONFIG_ARCH_FH8636)
#ifdef FH_CH0_USING_SCAN_G2
#define CH0_YUV_TYPE_G2 VPU_VOMODE_SCAN
#endif

#ifdef FH_CH0_USING_BLK_G2
#define CH0_YUV_TYPE_G2 VPU_VOMODE_BLK
#endif

#ifdef FH_CH0_USING_TILE192_G2
#define CH0_YUV_TYPE_G2 VPU_VOMODE_TILE192
#endif

#ifdef FH_CH0_USING_TILE224_G2
#define CH0_YUV_TYPE_G2 VPU_VOMODE_TILE224
#endif

#ifdef FH_CH0_USING_TILE256_G2
#define CH0_YUV_TYPE_G2 VPU_VOMODE_TILE256
#endif

#ifdef FH_CH0_USING_YUYV_G2
#define CH0_YUV_TYPE_G2 VPU_VOMODE_YUYV
#endif

#ifdef FH_CH0_USING_NV16_G2
#define CH0_YUV_TYPE_G2 VPU_VOMODE_NV16
#endif

#ifndef CH0_YUV_TYPE_G2
#define CH0_YUV_TYPE_G2 VPU_VOMODE_BLK
#endif

#ifdef FH_CH1_USING_SCAN_G2
#define CH1_YUV_TYPE_G2 VPU_VOMODE_SCAN
#endif

#ifdef FH_CH1_USING_BLK_G2
#define CH1_YUV_TYPE_G2 VPU_VOMODE_BLK
#endif

#ifdef FH_CH1_USING_TILE192_G2
#define CH1_YUV_TYPE_G2 VPU_VOMODE_TILE192
#endif

#ifdef FH_CH1_USING_TILE224_G2
#define CH1_YUV_TYPE_G2 VPU_VOMODE_TILE224
#endif

#ifdef FH_CH1_USING_TILE256_G2
#define CH1_YUV_TYPE_G2 VPU_VOMODE_TILE256
#endif

#ifdef FH_CH1_USING_YUYV_G2
#define CH1_YUV_TYPE_G2 VPU_VOMODE_YUYV
#endif

#ifdef FH_CH1_USING_NV16_G2
#define CH1_YUV_TYPE_G2 VPU_VOMODE_NV16
#endif

#ifndef CH1_YUV_TYPE_G2
#define CH1_YUV_TYPE_G2 VPU_VOMODE_BLK
#endif

#ifdef FH_CH2_USING_SCAN_G2
#define CH2_YUV_TYPE_G2 VPU_VOMODE_SCAN
#endif

#ifdef FH_CH2_USING_BLK_G2
#define CH2_YUV_TYPE_G2 VPU_VOMODE_BLK
#endif

#ifdef FH_CH2_USING_TILE192_G2
#define CH2_YUV_TYPE_G2 VPU_VOMODE_TILE192
#endif

#ifdef FH_CH2_USING_TILE224_G2
#define CH2_YUV_TYPE_G2 VPU_VOMODE_TILE224
#endif

#ifdef FH_CH2_USING_TILE256_G2
#define CH2_YUV_TYPE_G2 VPU_VOMODE_TILE256
#endif

#ifdef FH_CH2_USING_YUYV_G2
#define CH2_YUV_TYPE_G2 VPU_VOMODE_YUYV
#endif

#ifdef FH_CH2_USING_NV16_G2
#define CH2_YUV_TYPE_G2 VPU_VOMODE_NV16
#endif

#ifndef CH2_YUV_TYPE_G2
#define CH2_YUV_TYPE_G2 VPU_VOMODE_BLK
#endif

#ifdef FH_CH3_USING_SCAN_G2
#define CH3_YUV_TYPE_G2 VPU_VOMODE_SCAN
#endif

#ifdef FH_CH3_USING_NV16_G2
#define CH3_YUV_TYPE_G2 VPU_VOMODE_NV16
#endif

#ifdef FH_CH3_USING_RRGGBB_G2
#define CH3_YUV_TYPE_G2 VPU_VOMODE_RRGGBB
#endif

#ifdef FH_CH3_USING_RGB888_G2
#define CH3_YUV_TYPE_G2 VPU_VOMODE_RGB888
#endif

#else
#define CH0_YUV_TYPE_G2 VPU_VOMODE_SCAN
#define CH1_YUV_TYPE_G2 VPU_VOMODE_SCAN
#define CH2_YUV_TYPE_G2 VPU_VOMODE_SCAN
#define CH3_YUV_TYPE_G2 VPU_VOMODE_RGB888
#endif

#endif /* VIDEO_GRP2 */

#endif /*__chn_yuv_type_h__*/
