/**
 * Copyright (c) 2015-2019 Shanghai Fullhan Microelectronics Co., Ltd.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 *
 * Change Logs:
 * Date           Author       Notes
 * 2019-01-24     tangyh    the first version
 *
 */

#ifndef __CLOCK_CONFIG_H__
#define __CLOCK_CONFIG_H__

#include <rtdef.h>
#include "fh_clock.h"
#include "fh_pmu.h"

#define OSC_FREQUENCY  24000000   /*24M hz*/

#define RT_UINT9_MAX                    0x1ff
#define RT_UINT8_MAX                    0xff
#define RT_UINT7_MAX                    0x7f
#define RT_UINT6_MAX                    0x3f
#define RT_UINT5_MAX                    0x1f
#define RT_UINT4_MAX                    0xf
#define RT_UINT3_MAX                    0x7
#define RT_UINT2_MAX                    0x3
#define RT_UINT1_MAX                    0x1

struct clk  fh_clk_list[] = {
    {
        .name = "osc_clk",
        .clk_out_rate = OSC_FREQUENCY,
        .flag         = CLOCK_FIXED,
    },
    {
        .name = "pll_ddr_pclk",
        .flag = CLOCK_PLL_P,
        .clk_div.reg_offset = REG_PMU_PLL0,
        .clk_gate.reg_offset = REG_PMU_PLL0_CTRL,
        .clk_gate.mask = RT_UINT4_MAX<<8,
        .mult_parent = {"osc_clk"},
    },
    {
        .name = "pll_ddr_rclk",
        .flag = CLOCK_PLL_R,
        .clk_div.reg_offset = REG_PMU_PLL0,
        .clk_gate.reg_offset = REG_PMU_PLL0_CTRL,
        .clk_gate.mask = RT_UINT4_MAX<<12,
        .mult_parent = {"osc_clk"},
    },
    {
        .name = "pll_cpu_pclk",
        .flag = CLOCK_PLL_P,
        .clk_div.reg_offset = REG_PMU_PLL1,
        .clk_gate.reg_offset = REG_PMU_PLL1_CTRL,
        .clk_gate.mask = RT_UINT4_MAX<<8,
        .mult_parent = {"osc_clk"},
    },
    {
        .name = "pll_cpu_rclk",
        .flag = CLOCK_PLL_R,
        .clk_div.reg_offset = REG_PMU_PLL1,
        .clk_gate.reg_offset = REG_PMU_PLL1_CTRL,
        .clk_gate.mask = RT_UINT4_MAX<<12,
        .mult_parent = {"osc_clk"},
    },
    {
        .name = "cpu_div15_clk",
        .flag = DIV,
        .clk_div.reg_offset = REG_PMU_CLK_DIV5,
        .clk_div.div = 0xb,
        .clk_div.mask = RT_UINT8_MAX<<24,
        .clk_config = UNCONFIG,
        .mult_parent = {"pll_cpu_pclk"},
    },

    {
        .name = "ddr_clk",
        .flag = GATE,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE1,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<26,
        .clk_config = UNCONFIG,
        .mult_parent = {"pll_ddr_rclk"},
    },
    {
        .name = "cpu_fclk_p",
        .flag = MUX|DIV,
        .clk_mux.reg_offset = REG_PMU_SYS_CTRL,
        .clk_mux.mask = RT_UINT1_MAX<<3,
        .clk_div.reg_offset = REG_PMU_CLK_DIV6,
        .clk_div.mask = RT_UINT4_MAX<<8,
        .clk_config = UNCONFIG,
        .mult_parent = {"pll_cpu_pclk", "pll_ddr_pclk"},
    },
    {
        .name = "arm_clk",
        .flag = MUX,
        .clk_mux.reg_offset = REG_PMU_SYS_CTRL,
        .clk_mux.mask = RT_UINT1_MAX<<0,
        .clk_config = UNCONFIG,
        .mult_parent = {"osc_clk", "cpu_fclk_p"},
    },
    {
        .name = "arc_clk",
        .flag = DIV|GATE,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<22,
        .clk_div.reg_offset = REG_PMU_CLK_DIV6,
        .clk_div.mask = RT_UINT4_MAX<<12,
        .clk_config = UNCONFIG,
        .mult_parent = {"pll_cpu_pclk"},
    },
    {
        .name = "stm0_clk",
        .flag = DIV|GATE,
        .clk_div.reg_offset = REG_PMU_CLK_DIV0,
        .clk_div.mask = RT_UINT6_MAX<<0,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<2,
        .clk_config = UNCONFIG,
        .mult_parent = {"cpu_div15_clk"},
    },
    {
        .name = "isp_aclk",
        .flag = DIV,
        .clk_div.reg_offset = REG_PMU_CLK_DIV0,
        .clk_div.mask = RT_UINT6_MAX<<8,
#if defined(FH_USING_OPTIMIZATION_CLK)
        .clk_div.div = 14,
        .clk_config = CONFIG,
#elif defined(FH_USING_LOWPOWER_CLK)
        .clk_div.div = 15,
        .clk_config = CONFIG,
#else
        .clk_config = UNCONFIG,
#endif
        .mult_parent = {"pll_cpu_pclk"},
    },
    {
        .name = "ahb_clk",
        .flag = DIV|MUX,
        .clk_div.reg_offset = REG_PMU_CLK_DIV0,
        .clk_div.div = 0x1,
        .clk_div.mask = RT_UINT4_MAX<<16,
        .clk_mux.reg_offset = REG_PMU_SYS_CTRL,
        .clk_mux.mask = RT_UINT1_MAX<<0,
        .clk_config = UNCONFIG,
        .mult_parent = {"osc_clk", "pll_cpu_pclk"},
    },
    {
        .name = "veu_clk",
        .flag = DIV|GATE,
        .clk_div.reg_offset = REG_PMU_CLK_DIV0,
        .clk_div.mask = RT_UINT6_MAX<<24,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<4,
        .clk_config = UNCONFIG,
        .mult_parent = {"pll_cpu_pclk"},
     },
     {
        .name = "stm1_clk",
        .flag = DIV|GATE,
        .clk_div.reg_offset = REG_PMU_CLK_DIV1,
        .clk_div.mask = RT_UINT6_MAX<<0,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<3,
        .clk_config = UNCONFIG,
        .mult_parent = {"cpu_div15_clk"},
    },
    {
        .name = "mipi_cfg_clk",
        .flag = DIV|GATE,
        .clk_div.reg_offset = REG_PMU_CLK_DIV1,
        .clk_div.mask = RT_UINT6_MAX<<8,
        .clk_gate.reg_offset = REG_PMU_CLK_DIV7,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<4,
        .clk_config = UNCONFIG,
        .mult_parent = {"pll_cpu_pclk"},
    },
    {
        .name = "cis_clk_out",
        .flag = DIV|GATE|MUX,
        .clk_div.reg_offset = REG_PMU_CLK_DIV1,
        .clk_div.mask = RT_UINT8_MAX<<16,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<23,
        .clk_mux.reg_offset = REG_PMU_SYS_CTRL,
        .clk_mux.mask = RT_UINT1_MAX<<4,
        .clk_config = UNCONFIG,
        .mult_parent = {"osc_clk","pll_cpu_pclk"},
    },
    {
        .name = "efuse_clk",
        .flag = DIV|GATE,
        .clk_div.reg_offset = REG_PMU_CLK_DIV1,
        .clk_div.mask = RT_UINT6_MAX<<24,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<21,
        .clk_config = UNCONFIG,
        .mult_parent = {"cpu_div15_clk"},
    },
    {
        .name = "pts_clk",
        .flag = DIV|GATE,
        .clk_div.reg_offset = REG_PMU_CLK_DIV2,
        .clk_div.mask = RT_UINT9_MAX<<0,
        .clk_div.div = 0x63,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<19,
        .clk_config = CONFIG,
        .mult_parent = {"cpu_div15_clk"},
    },
    {
        .name = "I2C2_clk",
        .flag = DIV|GATE,
        .clk_div.reg_offset = REG_PMU_CLK_DIV2,
        .clk_div.mask = RT_UINT6_MAX<<12,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE1,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<5,
        .clk_config = UNCONFIG,
        .mult_parent = {"cpu_div15_clk"},
    },
    {
        .name = "uart2_clk",
        .flag = DIV|GATE,
        .clk_div.reg_offset = REG_PMU_CLK_DIV2,
        .clk_div.mask = RT_UINT6_MAX<<18,
        .clk_div.div = 0x5,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE1,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<6,
        .clk_config = CONFIG,
        .mult_parent = {"cpu_div15_clk"},
    },
    {
        .name = "pix_clk",
        .flag = DIV|GATE,
        .clk_div.reg_offset = REG_PMU_CLK_DIV2,
        .clk_div.mask = RT_UINT4_MAX<<24,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE1,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<23,
        .clk_config = UNCONFIG,
        .mult_parent = {"pll_cpu_pclk"},
    },
    {
        .name = "sdc0_clk2x",
        .flag = PREDIV|GATE|DIV,
        .pre_div = 4,
        .clk_div.reg_offset = REG_PMU_CLK_DIV3,
        .clk_div.mask = RT_UINT4_MAX<<8,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<9,
        .clk_config = UNCONFIG,
        .mult_parent = {"pll_cpu_rclk"},
    },

    {
        .name = "sdc1_clk2x",
        .flag = PREDIV|GATE|DIV,
        .pre_div = 4,
        .clk_div.reg_offset = REG_PMU_CLK_DIV3,
        .clk_div.mask = RT_UINT4_MAX<<24,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<10,
        .clk_config = UNCONFIG,
        .mult_parent = {"pll_cpu_rclk"},
    },
    {
        .name = "spi0_clk",
        .flag = DIV|GATE,
        .clk_div.reg_offset = REG_PMU_CLK_DIV3,
        .clk_div.mask = RT_UINT8_MAX<<0,
        .clk_div.div = 0x0,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<7,
        .clk_config = UNCONFIG,
        .mult_parent = {"pll_cpu_rclk"},
    },
    {
        .name = "spi1_clk",
        .flag = DIV|GATE,
        .clk_div.reg_offset = REG_PMU_CLK_DIV3,
        .clk_div.mask = RT_UINT4_MAX<<16,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<8,
        .clk_config = UNCONFIG,
        .mult_parent = {"pll_cpu_rclk"},
    },
    {
        .name = "spi2_clk",
        .flag = DIV|GATE,
        .clk_div.reg_offset = REG_PMU_CLK_DIV3,
        .clk_div.mask = RT_UINT4_MAX<<12,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<1,
        .clk_config = UNCONFIG,
        .mult_parent = {"pll_cpu_rclk"},
    },
    {
        .name = "uart0_clk",
        .flag = DIV|GATE,
        .clk_div.reg_offset = REG_PMU_CLK_DIV4,
        .clk_div.mask = RT_UINT6_MAX<<0,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<13,
        .clk_config = UNCONFIG,
        .mult_parent = {"cpu_div15_clk"},
    },
    {
        .name = "uart1_clk",
        .flag = DIV|GATE,
        .clk_div.reg_offset = REG_PMU_CLK_DIV4,
        .clk_div.mask = RT_UINT6_MAX<<8,
        .clk_div.div = 0x5,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<14,
        .clk_config = CONFIG,
        .mult_parent = {"cpu_div15_clk"},
    },
    {
        .name = "I2C0_clk",
        .flag = DIV|GATE,
        .clk_div.reg_offset = REG_PMU_CLK_DIV4,
        .clk_div.mask = RT_UINT6_MAX<<16,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<12,
        .clk_config = UNCONFIG,
        .mult_parent = {"cpu_div15_clk"},
    },
    {
        .name = "I2C1_clk",
        .flag = DIV|GATE,
        .clk_div.reg_offset = REG_PMU_CLK_DIV4,
        .clk_div.mask = RT_UINT6_MAX<<24,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<27,
        .clk_config = UNCONFIG,
        .mult_parent = {"cpu_div15_clk"},
    },
    {
        .name = "pwm_clk",
        .flag = DIV|GATE,
        .clk_div.reg_offset = REG_PMU_CLK_DIV5,
        .clk_div.mask = RT_UINT8_MAX<<0,
        .clk_div.div = 0x1,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<16,
        .clk_config = CONFIG,
        .mult_parent = {"cpu_div15_clk"},
    },
    {
        .name = "wdt_clk",
        .flag = DIV|GATE,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE1,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<27,
        .clk_div.reg_offset = REG_PMU_CLK_DIV5,
        .clk_div.mask = RT_UINT8_MAX<<8,
        .clk_div.div = 0x95,
        .clk_config = CONFIG,
        .mult_parent = {"ahb_clk"},
    },
    {
        .name = "tmr_clk",
        .flag = DIV|GATE,
        .clk_div.reg_offset = REG_PMU_CLK_DIV5,
        .clk_div.mask = RT_UINT8_MAX<<16,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<17,
        .clk_config = UNCONFIG,
        .mult_parent = {"cpu_div15_clk"},
    },
    {
        .name = "sadc_clk",
        .flag = DIV|GATE,
        .clk_div.reg_offset = REG_PMU_CLK_DIV6,
        .clk_div.mask = RT_UINT7_MAX<<16,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<26,
        .clk_config = UNCONFIG,
        .mult_parent = {"cpu_div15_clk"},
    },
    {
        .name = "ac_clk",
        .flag = DIV|GATE,
        .clk_div.reg_offset = REG_PMU_CLK_DIV6,
        .clk_div.mask = RT_UINT6_MAX<<0,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<11,
        .clk_config = UNCONFIG,
        .mult_parent = {"osc_clk"},
    },
    {
        .name = "eth_ref_clk",
        .flag = DIV|GATE,
        .clk_div.reg_offset = REG_PMU_CLK_DIV6,
        .clk_div.mask = RT_UINT4_MAX<<24,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<25,
        .clk_config = UNCONFIG,
        .mult_parent = {"cpu_div15_clk"},
    },
    {
        .name = "bgm_clk",
        .flag = DIV|GATE,
        .clk_div.reg_offset = REG_PMU_CLK_DIV7,
        .clk_div.mask = RT_UINT4_MAX<<0,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<18,
        .clk_config = UNCONFIG,
        .mult_parent = {"pll_cpu_pclk"},
    },
    {
        .name = "nn_clk",
        .flag = MUX|DIV|GATE,
        .clk_div.reg_offset = REG_PMU_CLK_DIV7,
        .clk_div.mask = RT_UINT6_MAX<<8,
        .clk_div.div = 3,
        .clk_gate.reg_offset = REG_PMU_CLK_DIV7,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<28,
        .clk_mux.reg_offset = REG_PMU_CLK_SEL,
        .clk_mux.mask = RT_UINT1_MAX<<6,
        .clk_config = UNCONFIG,
        .mult_parent = {"pll_cpu_rclk","pll_cpu_pclk"},
    },
    {
        .name = "jpeg_clk",
        .flag = DIV|GATE,
        .clk_div.reg_offset = REG_PMU_CLK_DIV7,
        .clk_div.mask = RT_UINT6_MAX<<16,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE1,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<30,
        .clk_config = UNCONFIG,
        .mult_parent = {"pll_cpu_pclk"},
    },
    {
        .name = "gpio0_db_clk",
        .flag = DIV|GATE|PREDIV,
        .pre_div = 100,
        .clk_div.reg_offset = REG_PMU_CLK_DIV8,
        .clk_div.mask = 0x3fff,
        .clk_gate.reg_offset = REG_PMU_CLK_DIV8,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<15,
        .clk_config = UNCONFIG,
        .mult_parent = {"cpu_div15_clk"},
    },
    {
        .name = "gpio1_db_clk",
        .flag = DIV|GATE|PREDIV,
        .pre_div = 100,
        .clk_div.reg_offset = REG_PMU_CLK_DIV8,
        .clk_div.mask = 0x3fff<<16,
        .clk_gate.reg_offset = REG_PMU_CLK_DIV8,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<31,
        .clk_config = UNCONFIG,
        .mult_parent = {"cpu_div15_clk"},
    },
    {
        .name = "jpeg_adapt_clk",
        .flag = GATE|CLOCK_FIXED,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<29,
        .clk_config = UNCONFIG,
    },
    {
        .name = "intc_hclk_gate",
        .flag = GATE|CLOCK_FIXED,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<31,
        .clk_config = UNCONFIG,
    },
    {
        .name = "ephy_clk_gate",
        .flag = GATE|CLOCK_FIXED,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE1,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<0,
        .clk_config = UNCONFIG,
    },
    {
        .name = "adapt_hclk_gate",
        .flag = GATE|CLOCK_FIXED,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE1,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<1,
        .clk_config = UNCONFIG,
    },
    {
        .name = "sdc0_clk8x_gate",
        .flag = GATE|CLOCK_FIXED,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE1,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<2,
        .clk_config = UNCONFIG,
    },
    {
        .name = "sdc1_clk8x_gate",
        .flag = GATE|CLOCK_FIXED,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE1,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<3,
        .clk_config = UNCONFIG,
    },
    {
        .name = "mipic_pclk_gate",
        .flag = GATE|CLOCK_FIXED,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE1,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<4,
        .clk_config = UNCONFIG,
    },
    {
        .name = "aes_hclk_gate",
        .flag = GATE|CLOCK_FIXED,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE1,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<7,
        .clk_config = UNCONFIG,
    },
    {
        .name = "usb_clk",
        .flag = GATE|CLOCK_FIXED,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE1,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<24,
        .clk_config = UNCONFIG,
    },
    {
        .name = "emac_hclk_gate",
        .flag = GATE|CLOCK_FIXED,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE1,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<25,
        .clk_config = UNCONFIG,
    },
    {
        .name = "rtc_hclk_gate",
        .flag = GATE|CLOCK_FIXED,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE1,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<28,
        .clk_config = UNCONFIG,
    },
    {
        .name = "mipi_wrap_gate",
        .flag = GATE|CLOCK_FIXED,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE1,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<29,
        .clk_config = UNCONFIG,
    },
    {
        .name = "jpg_hclk_gate",
        .flag = GATE,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE1,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<31,
        .clk_config = UNCONFIG,
        .mult_parent = {"eth_ref_clk"},
    },
    {
        .name = "mipi_dphy_clk",
        .flag = GATE|CLOCK_FIXED,
        .clk_gate.reg_offset = REG_PMU_CLK_DIV7,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<6,
        .clk_config = UNCONFIG,
    },
    {
        .name = "ephy_pclk_gate",
        .flag = GATE|CLOCK_FIXED,
        .clk_gate.reg_offset = REG_PMU_CLK_DIV7,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<7,
        .clk_config = UNCONFIG,
    },
    {
        .name = "veu_hclk_gate",
        .flag = GATE|CLOCK_FIXED,
        .clk_gate.reg_offset = REG_PMU_CLK_DIV7,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<25,
        .clk_config = UNCONFIG,
    },
    {
        .name = "veu_adapt_clk",
        .flag = GATE|CLOCK_FIXED,
        .clk_gate.reg_offset = REG_PMU_CLK_DIV7,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<26,
        .clk_config = UNCONFIG,
    },
    {
        .name = "veu_adapt_hclk",
        .flag = GATE|CLOCK_FIXED,
        .clk_gate.reg_offset = REG_PMU_CLK_DIV7,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<27,
        .clk_config = UNCONFIG,
    },
    {
        .name = "nn_hclk_gate",
        .flag = GATE|CLOCK_FIXED,
        .clk_gate.reg_offset = REG_PMU_CLK_DIV7,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<29,
        .clk_config = UNCONFIG,
    },
    {
        .name = "bgm_hclk_gate",
        .flag = GATE|CLOCK_FIXED,
        .clk_gate.reg_offset = REG_PMU_CLK_DIV7,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<31,
        .clk_config = UNCONFIG,
    },
    {
        .name = "gpio0_pclk_gate",
        .flag = GATE|CLOCK_FIXED,
        .clk_gate.reg_offset = REG_PMU_CLK_DIV8,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<14,
        .clk_config = UNCONFIG,
    },
    {
        .name = "gpio1_pclk_gate",
        .flag = GATE|CLOCK_FIXED,
        .clk_gate.reg_offset = REG_PMU_CLK_DIV8,
        .clk_gate.value = DEFAULT,
        .clk_gate.mask = RT_UINT1_MAX<<30,
        .clk_config = UNCONFIG,
    },
    {
        .name = "sdc0_clk_drv",
        .flag = PHASE,
        .clk_div.reg_offset = REG_PMU_CLK_GATE1,
        .clk_div.mask = RT_UINT3_MAX<<20,
        .clk_config = UNCONFIG,
        .mult_parent = {"sdc0_clk2x"},
    },
    {
        .name = "sdc0_clk_sample",
        .flag = PHASE,
        .clk_div.reg_offset = REG_PMU_CLK_GATE1,
        .clk_div.mask = RT_UINT3_MAX<<16,
        .clk_config = UNCONFIG,
        .mult_parent = {"sdc0_clk2x"},
    },
    {
        .name = "sdc1_clk_drv",
        .flag = PHASE,
        .clk_div.reg_offset = REG_PMU_CLK_GATE1,
        .clk_div.mask = RT_UINT3_MAX<<12,
        .clk_config = UNCONFIG,
        .mult_parent = {"sdc1_clk2x"},
    },
    {
        .name = "sdc1_clk_sample",
        .flag = PHASE,
        .clk_div.reg_offset = REG_PMU_CLK_GATE1,
        .clk_div.mask = RT_UINT3_MAX<<8,
        .clk_config = UNCONFIG,
        .mult_parent = {"sdc1_clk2x"},
    },

};
unsigned int fh_clock_cfg_count = ARRAY_SIZE(fh_clk_list);
#endif
